openapi: 3.0.0
info:
  title: Laravel React 掲示板課題 API仕様書
  description: Laravel React 掲示板課題 API仕様書
  version: 1.0.0

definitions:
  Success:
    type: object
    properties:
      status:
        type: string
        example: success
        description: 処理ステータス
      code:
        type: integer
        example: 200
        description: HTTPステータスコード
      message:
        type: string
        example: 'OK'
  AuthError: # テンプレート名
    type: object
    properties:
      status:
        type: string
        example: error
      errors:
        type: object
        properties:
          token:
            type: string
            example: トークンが無効 または 有効期限が切れています

paths:

  /api/register/create:
    post:
      tags:
        - register
      summary: ユーザー登録API
      description: ユーザー登録API
      requestBody:
        description: ユーザー登録時のリクエストボディ
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: ユーザー名（255文字まで）
                  type: string
                  example: 佐藤太郎
                email:
                  description: メールアドレス（一意、255文字まで）
                  type: string
                  example: hogehoge@gmail.com
                password:
                  description: パスワード（最小8文字）
                  type: string
                  example: password
              required:
                - name
                - email
                - password
      responses:
        '200':
          description: ユーザー登録成功時
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                    description: 処理ステータス
                  payload:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                        description: 仮登録ユーザーID
                      email:
                        type: string
                        maxLength: 256
                        example: example@example.com
                        description: メールアドレス
        '400':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                type: object
                properties:

        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/definitions/AuthError'

  /api/user/pre_register:
    post:
      tags:
        - register
      summary: ユーザー仮登録API
      description: | 
        ユーザー仮登録API
        - 仮登録メールを送信
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  maxLength: 256
                  example: example_user@example.com
                  description: メールアドレス
                name: 
                  type: string
                  example: exampleUser
                  description: |
                    ユーザー名
              required:
                - email
                - name
      responses:
        '200':
          definitions: 成功時レスポンス


  /api/user/register:
    post:
      tags:
        - register
      summary: ユーザー本登録API
      
